# src values
FLUID_MOD_NONE = 0
FLUID_MOD_VELOCITY = 2
FLUID_MOD_KEY = 3
FLUID_MOD_KEYPRESSURE = 10
FLUID_MOD_CHANNELPRESSURE = 13
FLUID_MOD_PITCHWHEEL = 14
FLUID_MOD_PITCHWHEELSENS = 16

# Transforms
FLUID_MOD_TRANSFORM_LINEAR = 0
FLUID_MOD_TRANSFORM_ABS = 2
